### ISSUE TITLE
Unclear and insufficient documentation to implement

### ISSUE THREAD

**Issue by jlarosa-utn** [Aninstance/simple-stock-management#23]
Please share a clear documentation, to be able to follow and implement this on a raspberry would be very useful for many people. Just think that the people who built Python and Django went out of their way to build a non-profit community. There are countries today that are in a difficult economic situation and need this type of application. 
Maybe with a document to contribute, you would have more followers and you could grow this product.

Thanks!

**Comment by Aninstance** [comment]
Thank you for your comment and expression of interest in this project. 

Unfortunately, I do not currently have the free time to create additional documentation for this particular project. As noted, there appears insufficient public interest to prioritise this over my other Open Source work, therefore although I'm presently pushing periodical security updates to the open source branch, this will only be the case for so long as I'm maintaining the proprietary branch for paying clients.

The crucial point here is that the open source branch you see here ***cannot be relied upon to be regularly maintained*** and should ***not*** be used in production unless maintained by a developer. It is ***not*** intended for the 'end user' and it would be inappropriate to encourage organisations and businesses to deploy this without having developers who are willing and able to commit to maintaining the project for as long as those organisations are using it.

I am being up-front about this: In the absence of appropriate funding, I cannot commit to maintain this project long-term. Therefore, additional documentation written for an end user would not only be time consuming to create and maintain, but actually misleading; the code is not a production-ready product. It is, at best, a prototype; the "product" is the docker build which I maintain and host as a service for paying clients - however I will be maintaining it for only so long as those clients are using it.

Many of us are struggling to make a living, so with all the will in the world, there is a limit to the time and energy we have to spend working on projects for which we receive no income. Such is the world we live in; we'd not get much coding done if we were unable to afford food or a roof over our heads.

You are, of course, welcome to fork the project and to use it as a basis upon which to build your own product.
