### ISSUE TITLE
Unable to configure handler 'file'

### ISSUE THREAD

**Issue by youssriaboelseod** [Aninstance/simple-stock-management#35]
hi Anistance
thanks for your system
but i got this eror Unable to configure handler 'file'
![image](https://user-images.githubusercontent.com/40850682/172117188-da582526-e0e3-44ba-8b46-a39749d8f6fd.png)

i think there some of directories not found

**Comment by Aninstance** [comment]
Hi,

You'd need to create the log file first. If you're on a linux system, you'd run:

`sudo mkdir -p /var/log/django`

Then:

`sudo touch /var/log/django/ssm.log`

Or, you could modify the configuration to write the log file elsewhere if you'd prefer.

**Comment by youssriaboelseod** [comment]
ok , thanks
